### ISSUE TITLE
Update available

### ISSUE THREAD

**Issue by caecos** [dizzisound/VCV_Csound#2]
Hi Daniele, the sources have been updated for the chorus and delay modules: https://github.com/Djack13/VCV_Csound

When you have some time on your hands I will wait for the Windows release...thx...

**Comment by dizzisound** [comment]
@caecos Nice, thank you for the notification! Tomorrow I'll sync the Win repo and commit both the sources and the binaries. Il'll let you know as soon as it's done. 
Best, 
d.z.

**Comment by caecos** [comment]
Grazie mille

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Daniele Zerbini <notifications@github.com>
Envoyé : Thursday, October 11, 2018 3:30:37 PM
À : dizzisound/VCV_Csound
Cc : caecos; Mention
Objet : Re: [dizzisound/VCV_Csound] Update available (#2)


@caecos<https://github.com/caecos> Nice, thank you for the notification! Tomorrow I'll sync the Win repo and commit both the sources and the binaries. Il'll let you know as soon as it's done.
Best,
d.z.

**Comment by dizzisound** [comment]
Done, sources and binaries were updated.
I am also watching the upstream repo from René now (I'd have sworn I already did it, but it was not like that).
:-)

**Comment by caecos** [comment]
Hey, works and compile flawlessly...many thank's...regards for all your help...
